In [24]:
import numpy as np

# 랜덤시드 고정시키기
np.random.seed(0)

from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing.image import array_to_img
from keras.preprocessing.image import img_to_array, load_img
from keras.preprocessing.image import load_img

# 데이터셋 불러오기
train_datagen = ImageDataGenerator(rescale=1./255, 
                                   rotation_range=15,
                                   width_shift_range=0.1,
                                   height_shift_range=0.1,
                                   shear_range=0.5,
                                   zoom_range=[0.8, 2.0],
                                   horizontal_flip=True,
                                   vertical_flip=True,
                                   fill_mode='nearest')

In [25]:
img = load_img('./src/circle_k.jpg')
x = img_to_array(img)
print(x.shape) # 24 X 24 칼라 이미지
print(x)

(24, 24, 3)
[[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[254. 254. 254.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]]


In [26]:
# 3차원 배열을 4차원으로 변경
x = x.reshape((1,) + x.shape)
print(x.shape)

(1, 24, 24, 3)


In [27]:
# 훈련 폴더와 검증 폴더의 생성
import os

newfolder='./train'
if os.path.exists(newfolder) == False:
    os.mkdir(newfolder)
newfolder='./train/circle'
if os.path.exists(newfolder) == False:
    os.mkdir(newfolder)   
newfolder='./train/rectangle'
if os.path.exists(newfolder) == False:
    os.mkdir(newfolder)   
newfolder='./train/triangle'
if os.path.exists(newfolder) == False:
    os.mkdir(newfolder)  
    
newfolder='./validation'
if os.path.exists(newfolder) == False:
    os.mkdir(newfolder)
newfolder='./validation/circle'
if os.path.exists(newfolder) == False:
    os.mkdir(newfolder)   
newfolder='./validation/rectangle'
if os.path.exists(newfolder) == False:
    os.mkdir(newfolder)   
newfolder='./validation/triangle'
if os.path.exists(newfolder) == False:
    os.mkdir(newfolder)      
    

### 훈련 및 검증 이미지 생성 (생성하려는 갯수보다 +1)

#### 검은색 계열 훈련용 80 개

In [28]:
img = load_img('./src/circle_k.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./train/circle', 
                                   save_prefix='k', 
                                   save_format='jpg'):
    i += 1
    if i >= 81: 
        break
        
img = load_img('./src/rectangle_k.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./train/rectangle', 
                                   save_prefix='k', 
                                   save_format='jpg'):
    i += 1
    if i >= 81: 
        break
        
        
img = load_img('./src/triangle_k.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./train/triangle', 
                                   save_prefix='k', 
                                   save_format='jpg'):
    i += 1
    if i >= 81: 
        break
        


#### 검은색 계열 검증용 20개

In [29]:
img = load_img('./src/circle_k.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./validation/circle', 
                                   save_prefix='k', 
                                   save_format='jpg'):
    i += 1
    if i >= 21: 
        break
        
img = load_img('./src/rectangle_k.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./validation/rectangle', 
                                   save_prefix='k', 
                                   save_format='jpg'):
    i += 1
    if i >= 21: 
        break
        
        
img = load_img('./src/triangle_k.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./validation/triangle', 
                                   save_prefix='k', 
                                   save_format='jpg'):
    i += 1
    if i >= 21: 
        break
        


#### 빨간색 계열 훈련용 80 개

In [31]:
img = load_img('./src/circle_r.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./train/circle', 
                                   save_prefix='r', 
                                   save_format='jpg'):
    i += 1
    if i >= 81: 
        break
        
img = load_img('./src/rectangle_r.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./train/rectangle', 
                                   save_prefix='r', 
                                   save_format='jpg'):
    i += 1
    if i >= 81: 
        break
        
        
img = load_img('./src/triangle_r.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./train/triangle', 
                                   save_prefix='r', 
                                   save_format='jpg'):
    i += 1
    if i >= 81: 
        break
        


#### 빨간색 계열 검증용 20개

In [32]:
img = load_img('./src/circle_r.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./validation/circle', 
                                   save_prefix='r', 
                                   save_format='jpg'):
    i += 1
    if i >= 21: 
        break
        
img = load_img('./src/rectangle_r.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./validation/rectangle', 
                                   save_prefix='r', 
                                   save_format='jpg'):
    i += 1
    if i >= 21: 
        break
        
        
img = load_img('./src/triangle_r.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./validation/triangle', 
                                   save_prefix='r', 
                                   save_format='jpg'):
    i += 1
    if i >= 21: 
        break
        


#### 파란색 계열 훈련용 80 개

In [33]:
img = load_img('./src/circle_b.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./train/circle', 
                                   save_prefix='b', 
                                   save_format='jpg'):
    i += 1
    if i >= 81: 
        break
        
img = load_img('./src/rectangle_b.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./train/rectangle', 
                                   save_prefix='b', 
                                   save_format='jpg'):
    i += 1
    if i >= 81: 
        break
        
        
img = load_img('./src/triangle_b.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./train/triangle', 
                                   save_prefix='b', 
                                   save_format='jpg'):
    i += 1
    if i >= 81: 
        break
        


#### 파란색 계열 검증용 20 개

In [34]:
img = load_img('./src/circle_b.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./validation/circle', 
                                   save_prefix='b', 
                                   save_format='jpg'):
    i += 1
    if i >= 21: 
        break
        
img = load_img('./src/rectangle_b.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./validation/rectangle', 
                                   save_prefix='b', 
                                   save_format='jpg'):
    i += 1
    if i >= 21: 
        break
        
        
img = load_img('./src/triangle_b.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)
i = 0

# 이 for는 무한으로 반복되기 때문에 우리가 원하는 반복횟수를 지정하여, 지정된 반복횟수가 되면 빠져나오도록 해야함
# 폴더를 미리 제작 할것
for batch in train_datagen.flow(x, batch_size=1, 
                                   save_to_dir='./validation/triangle', 
                                   save_prefix='b', 
                                   save_format='jpg'):
    i += 1
    if i >= 21: 
        break
        
