In [4]:
import warnings
warnings.filterwarnings(action='ignore')
# warnings.filterwarnings(action='default')

import tensorflow as tf

In [7]:
# 일반적인 언어의 형태
a = 1
b = 2
c = a + b
print(a)
print(c)

1
3


In [8]:
# 그래프 선언
a = tf.constant(1,name='a') # name : Tensorflow에서 사용하는 변수명(왼쪽:파이썬변수,오른쪽:Tensorflow변수)
b = tf.constant(2,name='b')
c = a + b
print(type(a))
print(a)
print(c)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("a_2:0", shape=(), dtype=int32)
Tensor("add_2:0", shape=(), dtype=int32)


In [11]:
# 실행
session = tf.Session()
print(session.run(a))
print(session.run(c))
session.close()

1
3


In [12]:
with tf.Session() as session : # 자동 close
    print(session.run(c))
    

3


In [15]:
graph = tf.get_default_graph()
print(graph.as_graph_def())

node {
  name: "a"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "b"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "add"
  op: "Add"
  input: "a"
  input: "b"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "a_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "b_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    ke

In [20]:
a = tf.Variable(1,name='a')
b = tf.Variable(2,name='b')
c = a + b
print(a)
print(c)

<tf.Variable 'a_4:0' shape=() dtype=int32_ref>
Tensor("add_4:0", shape=(), dtype=int32)


In [21]:
with tf.Session() as session :
    session.run(tf.global_variables_initializer()) # 변수 초기화
    print(a)
    print(b)
    print(c)
    print(session.run(a))
    print(session.run(b))
    print(session.run(c))

<tf.Variable 'a_4:0' shape=() dtype=int32_ref>
<tf.Variable 'b_4:0' shape=() dtype=int32_ref>
Tensor("add_4:0", shape=(), dtype=int32)
1
2
3


In [30]:
# 변수의 사용 1,2
d = tf.Variable(1,name='d')
e = tf.Variable(2,name='e')
f = tf.Variable(0,name='f')

#tf.assign(f,d +e) # d + e --> f에 할당, (잘 안됨)
f = d + e  # d + e --> f에 할당
with tf.Session() as session :
    session.run(tf.global_variables_initializer()) # 변수 초기화
    print('d: ', session.run(d))
    print('e: ', session.run(e))
    print('f: ', session.run(f))


d:  1
e:  2
f:  3


In [34]:
# 변수의 사용 3
d = tf.Variable(1,name='d')
e = tf.Variable(2,name='e')

f = tf.assign(d ,d +e) # d + e --> d에 할당, 결과를 f로 리턴

with tf.Session() as session :
    session.run(tf.global_variables_initializer()) # 변수 초기화
    print('d: ', session.run(d)) # 1
    print('f: ', session.run(f)) # 3
    print('d: ', session.run(d)) # f조리한 이후 d 출력

d:  1
f:  3
d:  3


In [37]:
# placeholder: 파이썬의 값을 텐서플로의 그래프로 전달
ph = tf.placeholder(dtype=tf.int32, name='ph') # 연산을 실행 할 수 없음.
a = tf.constant(1, name='a')
b = ph + a

with tf.Session() as session:
    print('ph + a = ', session.run(b, feed_dict={ph: 10})) # python --> tensorflow 값 대입

ph + a =  11


In [39]:
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')

c = tf.add(a, b)
d = tf.subtract(a, b)
e = tf.multiply(a, b)
f = tf.divide(c, b)

with tf.Session() as session:
    print('a+b=', session.run(c))
    print('a-b=', session.run(d))
    print('a*b=', session.run(e))
    print('a/b=', session.run(f))
    g = a + b
    print('g=', session.run(g))
    h = tf.mod(c,b)
    print('h=', session.run(h))

a+b= 5
a-b= -1
a*b= 6
a/b= 1.6666666666666667
g= 5
h= 2


In [40]:
a = tf.constant([1, 2, 3], name='a')
b = tf.constant([4, 5, 6], name='b')
c = a + b

with tf.Session() as session:
    print('a+b:', session.run(c))

a+b: [5 7 9]


In [41]:
a = tf.constant([[1, 2], [3, 4]], name='a')
b = tf.constant([[1], [2]], name='b')
# 행렬의 곱의 결과: 첫번째 행렬의 행, 두번째 행렬의 열, 2행 2열 * 2행 1열 = 2행 1열 
# 행렬의 곱의 조건: 첫번째 행렬의 열과 두번째 행렬의 행의 값이 같아야함.
c = tf.matmul(a, b)  
d = tf.constant([1, 2, 3], name='d')

print('shape of a:', a.shape)
print('shape of b', b.shape)
print('shape of c', c.shape)
print('shape of d', d.shape)

with tf.Session() as session:
    print(session.run(a))
    print(session.run(b))
    print('--------------------')
    print(session.run(c))
    print('--------------------')
    print(session.run(d))

shape of a: (2, 2)
shape of b (2, 1)
shape of c (2, 1)
shape of d (3,)
[[1 2]
 [3 4]]
[[1]
 [2]]
--------------------
[[ 5]
 [11]]
--------------------
[1 2 3]


In [42]:
# 2차원 배열, 행의수는 무제한, 열의 수는 2 고정
a = tf.placeholder(shape=(None, 2), dtype=tf.int32, name='a') 

with tf.Session() as session:
    # print('a=', session.run(a, feed_dict={a: [1]}))    # ERROR
    # print('a=', session.run(a, feed_dict={a: [1, 2]})) # ERROR
    print('a=', session.run(a, feed_dict={a: [[1, 2]]}))
    print('a=', session.run(a, feed_dict={a: [[1, 2], [3, 4]]}))
    print('a=', session.run(a, feed_dict={a: [[1, 2], [3, 4], [5, 6]]}))
    # print('a=', session.run(a, feed_dict={a: [[1], [3], [5]]})) # ERROR, 열의 수가 틀림

a= [[1 2]]
a= [[1 2]
 [3 4]]
a= [[1 2]
 [3 4]
 [5 6]]


In [1]:
# Tensorboard 사용
# 그래프 초기화는 커널을 Restart 할 것
# (machine) C:\Windows\system32> tensorboard --logdir=C:\ai_201909\doc\ws_python\notebook\logs
# 접속: http://soldesk-PC:6006
import tensorflow as tf

a = tf.constant(1, name='a')
b = tf.constant(1, name='b')
c = a + b

LOG_DIR = '../../logs' # 폴더는 자동 생성됨. /ws_python/notebook/logs
graph = tf.get_default_graph()
with tf.summary.FileWriter(LOG_DIR) as writer:
    writer.add_graph(graph)    