In [4]:
import warnings
warnings.filterwarnings(action='ignore')
# warnings.filterwarnings(action='default')
 
import matplotlib.pyplot as plt
%matplotlib inline

import tensorflow as tf

In [5]:
# 일반적인 언어의 형태
a = 1
b = 2
c = a + b
print(c)

3


In [6]:
# 그래프 선언
a = tf.constant(1, name='a') # name='a': Tensorflow에서 사용하는 변수명
b = tf.constant(2, name='b')
c = a + b
print(type(a))
print(a)
print(c)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("a:0", shape=(), dtype=int32)
Tensor("add:0", shape=(), dtype=int32)


In [7]:
# 실행
session = tf.Session()
print(session.run(c))
session.close()

3


In [8]:
with tf.Session() as session:  # 자동 close
    print(session.run(c))

3


In [9]:
graph = tf.get_default_graph()
print(graph.as_graph_def())

node {
  name: "a"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "b"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "add"
  op: "Add"
  input: "a"
  input: "b"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
versions {
  producer: 24
}



In [10]:
# 변수의 사용
a = tf.Variable(1, name='a')
b = tf.Variable(2, name='b')
c = a + b
print(a)
print(c)

<tf.Variable 'a_1:0' shape=() dtype=int32_ref>
Tensor("add_1:0", shape=(), dtype=int32)


In [14]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())  # 변수 초기화
    print(a)
    print(b)
    print(c)
    print(session.run(a))
    print(session.run(b))
    print(session.run(c))

<tf.Variable 'a_1:0' shape=() dtype=int32_ref>
<tf.Variable 'b_1:0' shape=() dtype=int32_ref>
Tensor("add_1:0", shape=(), dtype=int32)
1
2
3


In [18]:
# 변수의 사용 1
d = tf.Variable(1, name='d')
e= tf.Variable(2, name='e')
f= tf.Variable(0, name='f')

f = d + e # d + e -> f에 할당
with tf.Session() as session:
    session.run(tf.global_variables_initializer())  # 변수 초기화
    print('d:', session.run(d))
    print('f:', session.run(f)) # 3

d: 1
f: 0


In [20]:
# 변수의 사용 2
d = tf.Variable(1, name='d')
e= tf.Variable(2, name='e')
f= tf.Variable(0, name='f')

tf.assign(f, d + e) # d + e -> f에 할당
with tf.Session() as session:
    session.run(tf.global_variables_initializer())  # 변수 초기화
    print('d:', session.run(d))
    print('f:', session.run(f)) # 0

d: 1
f: 0


In [22]:
# 변수의 사용 3
d = tf.Variable(1, name='d')
e= tf.Variable(2, name='e')

f = tf.assign(d, d + e) # d + e -> d에 할당하고 결과를 f로 리턴
with tf.Session() as session:
    session.run(tf.global_variables_initializer())  # 변수 초기화
    print('d:', session.run(d)) # 1
    print('f:', session.run(f)) # 3
    print('d:', session.run(d)) # 3

d: 1
f: 3
d: 3


In [26]:
# placeholder: 파이썬의 값을 텐서플로의 그래프로 전달
ph = tf.placeholder(dtype=tf.int32, name='ph') # 연산을 실행 할 수 없음.
a = tf.constant(1, name='a')
b = ph + a

with tf.Session() as session:
    print('ph+a=', session.run(b, feed_dict={ph: 10})) # python --> tensorflow 값 대입

ph+a= 11


In [28]:
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')

c = a + b
d = a - b
e = a * b
f = c / b

with tf.Session() as session:
    print('a+b=', session.run(c))
    print('a-b=', session.run(d))
    print('a*b=', session.run(e))
    print('a/b=', session.run(f))
    g = a + b
    print('g=', session.run(g))
    h = a % b
    print('g=', session.run(h))    

a+b= 5
a-b= -1
a*b= 6
a/b= 1.6666666666666667
g= 5
g= 2


In [30]:
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')

c = tf.add(a, b)
d = tf.subtract(a, b)
e = tf.multiply(a, b)
f = tf.divide(c, b)

with tf.Session() as session:
    print('a+b=', session.run(c))
    print('a-b=', session.run(d))
    print('a*b=', session.run(e))
    print('a/b=', session.run(f))
    g = a + b
    print('g=', session.run(g))
    h = tf.mod(c, b)
    print('g=', session.run(h))  

a+b= 5
a-b= -1
a*b= 6
a/b= 1.6666666666666667
g= 5
g= 2


In [31]:
a = tf.constant([1, 2, 3], name='a')
b = tf.constant([4, 5, 6], name='b')
c = a + b

with tf.Session() as session:
    print('a+b:', session.run(c))

a+b: [5 7 9]


In [33]:
a = tf.constant([[1, 2], [3, 4]], name='a')
b = tf.constant([[1], [2]], name='b')
# 행렬의 곱의 결과: 첫번째 행렬의 행, 두번째 행렬의 열, 2행 2열 * 2행 1열 = 2행 1열 
# 행렬의 곱의 조건: 첫번째 행렬의 열과 두번째 행렬의 행의 값이 같아야함.
c = tf.matmul(a, b)  
d = tf.constant([1, 2, 3], name='d')

print('shape of a:', a.shape)
print('shape of b', b.shape)
print('shape of c', c.shape)
print('shape of d', d.shape)

with tf.Session() as session:
    print(session.run(a))
    print(session.run(b))
    print('--------------------')
    print(session.run(c))
    print('--------------------')
    print(session.run(d))

shape of a: (2, 2)
shape of b (2, 1)
shape of c (2, 1)
shape of d (3,)
[[1 2]
 [3 4]]
[[1]
 [2]]
--------------------
[[ 5]
 [11]]
--------------------
[1 2 3]


In [36]:
# 2차원 배열, 행의수는 무제한, 열의 수는 2 고정
a = tf.placeholder(shape=(None, 2), dtype=tf.int32, name='a') 

with tf.Session() as session:
    # print('a=', session.run(a, feed_dict={a: [1]}))    # ERROR
    # print('a=', session.run(a, feed_dict={a: [1, 2]})) # ERROR
    print('a=', session.run(a, feed_dict={a: [[1, 2]]}))
    print()
    print('a=', session.run(a, feed_dict={a: [[1, 2], [3, 4]]}))
    print()
    print('a=', session.run(a, feed_dict={a: [[1, 2], [3, 4], [5, 6]]}))
    # print('a=', session.run(a, feed_dict={a: [[1], [3], [5]]})) # ERROR, 열의 수가 틀림


a= [[1 2]]

a= [[1 2]
 [3 4]]

a= [[1 2]
 [3 4]
 [5 6]]


In [1]:
# Tensorboard 사용
# 그래프 초기화는 커널을 Restart 할 것
# (machine) C:\Windows\system32> tensorboard --logdir=C:/ai_201909/ws_python/notebook/logs
# 접속: http://soldesk-PC:6006
import tensorflow as tf

a = tf.constant(1, name='a')
b = tf.constant(1, name='b')
c = a + b

LOG_DIR = '../../logs' # 폴더는 자동 생성됨. /ws_python/notebook/logs
graph = tf.get_default_graph()
with tf.summary.FileWriter(LOG_DIR) as writer:
    writer.add_graph(graph)  
    
    
    