In [16]:
import warnings
warnings.filterwarnings(action='ignore')
# warnings.filterwarnings(action='default')

import os,sys
import numpy as np
import pandas as pd
import seaborn as sb
from seaborn import pairplot

from keras.models import Sequential # Class
from keras.models import load_model # model 사용
from keras.layers import Dense # Class
from keras.layers import Dropout # Dropout 처리
from keras.callbacks import EarlyStopping  # 학습 자동 중지
from keras.callbacks import ModelCheckpoint # 우수한 학습모델 저장
from keras import regularizers
from keras.utils import to_categorical

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split # 학습셋과 테스트셋의 분리 지원
from sklearn.model_selection import StratifiedKFold  # K겹 교차 검증

import matplotlib
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

font_name = font_manager.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name()
# windows 10
# font_name = font_manager.FontProperties(fname="C:/Windows/Fonts/malgunsl.ttf").get_name()
rc('font', family=font_name)           # 맑은 고딕 폰트 지정
plt.rcParams["font.size"] = 12         # 글자 크기
# plt.rcParams["figure.figsize"] = (10, 4) # 10:4의 그래프 비율
plt.rcParams['axes.unicode_minus'] = False  # minus 부호는 unicode 적용시 한글이 깨짐으로 설정

%matplotlib inline

In [17]:
model = load_model('./Iris1.h5')

In [18]:
df_test = pd.read_csv('./iris_test_1.csv', names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"])
#df_val = pd.read_csv('./iris_val.csv', names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"])
print('1) df.head()')
print(df.head())

1) df.head()
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.0          3.5           1.3          0.3  Iris-setosa
1           4.5          2.3           1.3          0.3  Iris-setosa
2           4.4          3.2           1.3          0.2  Iris-setosa
3           5.0          3.5           1.6          0.6  Iris-setosa
4           5.1          3.8           1.9          0.4  Iris-setosa


In [19]:
data = df.values
print(type(data))
X = data[:, 0:4].astype(float)  # 행렬, 2차원 배열
print(X[0:5, 0:4])
Y_obj = data[:, 4]  # 1차원 배열
print(Y_obj[0:5])

<class 'numpy.ndarray'>
[[5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [20]:
data_test = df_test.values
print(type(data_test))

X_test = data_test[:, 0:4].astype(float)  # 행렬, 2차원 배열
print(X_test[0:5, 0:4])
print(X_test.shape)

Y_obj_test = data_test[:, 4]  # 1차원 배열
print(Y_obj[0:5])
print(Y_obj.shape)

e = LabelEncoder() # 문자열을 숫자로 그룹화해서 변경, 문자코드 순서 적용
e.fit(Y_obj)   # 품종 3가지
Y = e.transform(Y_obj)  # 0, 1, 2 정수로 변환 (알파벳 순으로 숫자부여)
print(Y)
print(len(Y))

<class 'numpy.ndarray'>
[[5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]]
(30, 4)
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']
(30,)
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
30


In [29]:
yp = model.predict(X_test) ## 모델 사용

print(X_test.shape)
print(yp.shape)

print(X_test[0])
print(yp[0])
print(np.argmax(yp[0]))

print(X_test[11])
print(yp[11])
print(np.argmax(yp[11]))

print(X_test[21])
print(yp[21])
print(np.argmax(yp[21]))

(30, 4)
(30, 3)
[5.  3.5 1.3 0.3]
[9.9846077e-01 1.5392173e-03 3.5957948e-11]
0
[6.4 3.2 4.5 1.5]
[5.9969194e-04 9.8444724e-01 1.4953003e-02]
1
[5.8 2.7 5.1 1.9]
[2.1386336e-07 2.6138790e-02 9.7386104e-01]
2


In [30]:
for item in yp :
    print(np.max(item),' index:', np.argmax(item))

0.99846077  index: 0
0.9759197  index: 0
0.997124  index: 0
0.99510795  index: 0
0.9968347  index: 0
0.99519956  index: 0
0.99880755  index: 0
0.99704486  index: 0
0.9988438  index: 0
0.99776936  index: 0
0.99593323  index: 1
0.98444724  index: 1
0.97387326  index: 1
0.9194792  index: 1
0.9505768  index: 1
0.9015294  index: 1
0.9407942  index: 1
0.9867007  index: 1
0.99014014  index: 1
0.9257715  index: 1
0.99946374  index: 2
0.97386104  index: 2
0.97750264  index: 2
0.96145934  index: 2
0.9957059  index: 2
0.9952427  index: 2
0.95064396  index: 2
0.97115177  index: 2
0.98487747  index: 2
0.99137795  index: 2
