In [15]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import load_model
import numpy as np

model = load_model('./actor.h5')

In [16]:
validation_datagen = ImageDataGenerator(rescale=1./255)

validation_generator = validation_datagen.flow_from_directory(
        './validation',
        target_size=(64, 64),    
        batch_size=1,
        class_mode='categorical')

Found 50 images belonging to 5 classes.


In [17]:
def display(data):
    # print(data)
    # print(type(data))
    sw= np.argmax(data, axis=0) # 0:열, 1: 행
    # print('sw:', sw)

    if sw == 0:
        sw = 'Amanda Seyfried'
    elif sw == 1:
        sw = 'Andrew Lincoln'
    elif sw == 2:
        sw = 'Anne Hathaway'
    elif sw == 3:
        sw = 'Keira Christina Knightley'        
    elif sw == 4:
        sw = 'Pierce Brosnan'        
        
    return sw    

output = model.predict_generator(validation_generator)
# numpy 출력 옵션 변경
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(validation_generator.class_indices) # 클래스명(폴더명) 출력
print(output)
print(type(output))

for item in output:
    print(display(item))    


{'Amanda Seyfried': 0, 'Andrew Lincoln': 1, 'Anne Hathaway': 2, 'Keira Christina Knightley': 3, 'Pierce Brosnan': 4}
[[0.335 0.024 0.604 0.017 0.019]
 [0.012 0.013 0.008 0.014 0.952]
 [0.000 0.000 0.874 0.126 0.000]
 [0.000 0.166 0.414 0.420 0.000]
 [0.003 0.539 0.454 0.003 0.001]
 [0.000 0.000 0.013 0.987 0.000]
 [0.960 0.009 0.023 0.007 0.000]
 [0.772 0.000 0.003 0.224 0.000]
 [0.997 0.000 0.000 0.001 0.002]
 [0.000 0.000 0.041 0.959 0.000]
 [0.003 0.164 0.007 0.826 0.000]
 [0.000 0.011 0.807 0.182 0.000]
 [0.000 0.000 0.998 0.002 0.000]
 [0.000 0.000 0.005 0.994 0.000]
 [0.217 0.000 0.000 0.783 0.000]
 [0.000 1.000 0.000 0.000 0.000]
 [0.998 0.000 0.001 0.000 0.000]
 [0.006 0.990 0.002 0.001 0.001]
 [0.000 0.000 0.986 0.014 0.000]
 [0.000 0.000 1.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 1.000]
 [0.000 0.000 0.001 0.000 0.998]
 [0.048 0.000 0.951 0.000 0.001]
 [0.002 0.026 0.075 0.045 0.853]
 [0.977 0.004 0.008 0.011 0.000]
 [0.000 0.999 0.001 0.000 0.000]
 [0.000 1.000 0.000 0.000

In [20]:
use_datagen = ImageDataGenerator(rescale=1./255)
use_generator = use_datagen.flow_from_directory('./use1',target_size=(64, 64), batch_size=1,class_mode='categorical')
output = model.predict_generator(use_generator, steps=1)
print('Amanda Seyfried:', display(output[0]),'\n')

use_generator = use_datagen.flow_from_directory('./use2',target_size=(64, 64), batch_size=1,class_mode='categorical')
output = model.predict_generator(use_generator, steps=1)
print('Andrew Lincoln:',display(output[0]),'\n')

use_generator = use_datagen.flow_from_directory('./use3',target_size=(64, 64), batch_size=1,class_mode='categorical')
output = model.predict_generator(use_generator, steps=1)
print('Anne Hathaway:',display(output[0]),'\n')

use_generator = use_datagen.flow_from_directory('./use4',target_size=(64, 64), batch_size=1,class_mode='categorical')
output = model.predict_generator(use_generator, steps=1)
print('Keira Christina Knightley:',display(output[0]),'\n')
 
use_generator = use_datagen.flow_from_directory('./use5',target_size=(64, 64), batch_size=1,class_mode='categorical')
output = model.predict_generator(use_generator, steps=1)
print('Pierce Brosnan:',display(output[0]),'\n')




Found 1 images belonging to 1 classes.
Amanda Seyfried: Amanda Seyfried 

Found 1 images belonging to 1 classes.
Andrew Lincoln: Andrew Lincoln 

Found 1 images belonging to 1 classes.
Anne Hathaway: Anne Hathaway 

Found 1 images belonging to 1 classes.
Keira Christina Knightley: Keira Christina Knightley 

Found 1 images belonging to 1 classes.
Pierce Brosnan: Pierce Brosnan 

