In [1]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import load_model
import numpy as np

model = load_model('./actor.h5')

Using TensorFlow backend.


In [2]:
validation_datagen = ImageDataGenerator(rescale=1./255)

validation_generator = validation_datagen.flow_from_directory(
        './validation',
        target_size=(64, 64),    
        batch_size=1,
        class_mode='categorical')

Found 60 images belonging to 6 classes.


In [3]:
def display(data):
    # print(data)
    # print(type(data))
    sw= np.argmax(data, axis=0) # 0:열, 1: 행
    # print('sw:', sw)

    if sw == 0:
        sw = 'Amanda Seyfried'
    elif sw == 1:
        sw = 'Andrew Lincoln'
    elif sw == 2:
        sw = 'Anne Hathaway'
    elif sw == 3:
        sw = 'Keira Christina Knightley'        
    elif sw == 4:
        sw = 'Pierce Brosnan'        
    elif sw == 5:
        sw = '조정석'        
        
    return sw    

output = model.predict_generator(validation_generator)
# numpy 출력 옵션 변경
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(validation_generator.class_indices) # 클래스명(폴더명) 출력
print(output)
print(type(output))

for item in output:
    print(display(item))    


{'Amanda Seyfried': 0, 'Andrew Lincoln': 1, 'Anne Hathaway': 2, 'JoJeongSuk': 3, 'Keira Christina Knightley': 4, 'Pierce Brosnan': 5}
[[0.963 0.009 0.021 0.000 0.001 0.006]
 [0.613 0.032 0.067 0.000 0.266 0.022]
 [0.505 0.012 0.001 0.000 0.022 0.461]
 [0.000 0.000 0.015 0.985 0.000 0.000]
 [0.000 1.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.001 0.999 0.000 0.000]
 [0.071 0.384 0.000 0.003 0.004 0.537]
 [0.000 0.000 0.778 0.000 0.222 0.000]
 [0.051 0.008 0.645 0.000 0.145 0.151]
 [0.998 0.000 0.000 0.000 0.001 0.000]
 [0.009 0.014 0.011 0.001 0.961 0.003]
 [0.003 0.009 0.862 0.000 0.125 0.001]
 [0.000 0.000 0.878 0.120 0.002 0.000]
 [0.000 0.000 0.001 0.999 0.000 0.000]
 [0.000 0.861 0.107 0.028 0.001 0.003]
 [0.000 0.187 0.554 0.022 0.237 0.000]
 [0.001 0.000 0.324 0.000 0.675 0.000]
 [0.000 0.000 0.992 0.000 0.008 0.000]
 [0.352 0.316 0.014 0.000 0.141 0.177]
 [0.000 0.000 0.000 0.000 0.000 1.000]
 [0.000 0.000 0.996 0.001 0.003 0.000]
 [0.002 0.000 0.000 0.000 0.000 0.998]
 [0.000 

In [5]:
use_datagen = ImageDataGenerator(rescale=1./255)
use_generator = use_datagen.flow_from_directory('./use1',target_size=(64, 64), batch_size=1,class_mode='categorical')
output = model.predict_generator(use_generator, steps=1)
print('Amanda Seyfried:', display(output[0]),'\n')

use_generator = use_datagen.flow_from_directory('./use2',target_size=(64, 64), batch_size=1,class_mode='categorical')
output = model.predict_generator(use_generator, steps=1)
print('Andrew Lincoln:',display(output[0]),'\n')

use_generator = use_datagen.flow_from_directory('./use3',target_size=(64, 64), batch_size=1,class_mode='categorical')
output = model.predict_generator(use_generator, steps=1)
print('Anne Hathaway:',display(output[0]),'\n')

use_generator = use_datagen.flow_from_directory('./use4',target_size=(64, 64), batch_size=1,class_mode='categorical')
output = model.predict_generator(use_generator, steps=1)
print('Keira Christina Knightley:',display(output[0]),'\n')
 
use_generator = use_datagen.flow_from_directory('./use5',target_size=(64, 64), batch_size=1,class_mode='categorical')
output = model.predict_generator(use_generator, steps=1)
print('Pierce Brosnan:',display(output[0]),'\n')

use_generator = use_datagen.flow_from_directory('./use6',target_size=(64, 64), batch_size=1,class_mode='categorical')
output = model.predict_generator(use_generator, steps=1)
print('조정석:',display(output[0]),'\n')

Found 1 images belonging to 1 classes.
Amanda Seyfried: Amanda Seyfried 

Found 1 images belonging to 1 classes.
Andrew Lincoln: Andrew Lincoln 

Found 1 images belonging to 1 classes.
Anne Hathaway: Anne Hathaway 

Found 1 images belonging to 1 classes.
Keira Christina Knightley: Pierce Brosnan 

Found 1 images belonging to 1 classes.
Pierce Brosnan: 조정석 

Found 1 images belonging to 1 classes.
JoJeongSuk: Keira Christina Knightley 

